eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    hostname: localhost

microservice:
 vendor-service:
  endpoints:
   endpoint:
    uri:http://VENDOR-SERVICE/vendor/save
 recruiter-service:
  endpoints:
   endpoint:
    uri:http://RECRUITER-SERVICE/recruiter/save
